// Auto-generated from CSV header: 21-22 Fall Split  - 21-22 Fall Regional 1.csv
// Types: TEXT, INTEGER, BOOLEAN, TIMESTAMPTZ, DOUBLE PRECISION

export const createStatsTableSql = `
CREATE TABLE IF NOT EXISTS stats (
  id BIGSERIAL PRIMARY KEY,
  "Player Name" TEXT,
  "Player ID" TEXT,
  "Date" TIMESTAMPTZ,
  "Season" TEXT,
  "Split" TEXT,
  "Regional" TEXT,
  "Day" INTEGER,
  "Stage" TEXT,
  "Round" INTEGER,
  "Best of " INTEGER,
  "Game Number" INTEGER,
  "Game" INTEGER,
  "Team" TEXT,
  "Victory" BOOLEAN,
  "OT" BOOLEAN,
  "Closest to Ball_All Zones" DOUBLE PRECISION,
  "Closest to Ball_Defense Zone" DOUBLE PRECISION,
  "Closest to Ball_Neutral Zone" DOUBLE PRECISION,
  "Closest to Ball_Offense Zone" DOUBLE PRECISION,
  "Furthest from Ball_All Zones" DOUBLE PRECISION,
  "Furthest from Ball_Defense Zone" DOUBLE PRECISION,
  "Furthest from Ball_Neutral Zone" DOUBLE PRECISION,
  "Furthest from Ball_Offense Zone" DOUBLE PRECISION,
  "First man_All Zones" DOUBLE PRECISION,
  "First man_Defense Zone" DOUBLE PRECISION,
  "First man_Neutral Zone" DOUBLE PRECISION,
  "First man_Offense Zone" DOUBLE PRECISION,
  "Last man_All Zones" DOUBLE PRECISION,
  "Last man_Defense Zone" DOUBLE PRECISION,
  "Last man_Neutral Zone" DOUBLE PRECISION,
  "Last man_Offense Zone" DOUBLE PRECISION,
  "Left Side_All Zones" DOUBLE PRECISION,
  "Left Side_Defense Zone" DOUBLE PRECISION,
  "Left Side_Neutral Zone" DOUBLE PRECISION,
  "Left Side_Offense Zone" DOUBLE PRECISION,
  "Right Side_All Zones" DOUBLE PRECISION,
  "Right Side_Defense Zone" DOUBLE PRECISION,
  "Right Side_Neutral Zone" DOUBLE PRECISION,
  "Right Side_Offense Zone" DOUBLE PRECISION,
  "Ball Touches_All Zones" DOUBLE PRECISION,
  "Ball Touches_Defense Zone" DOUBLE PRECISION,
  "Ball Touches_Neutral Zone" DOUBLE PRECISION,
  "Ball Touches_Offense Zone" DOUBLE PRECISION,
  "Time on Ball_All Zones" DOUBLE PRECISION,
  "Time on Ball_Defense Zone" DOUBLE PRECISION,
  "Time on Ball_Neutral Zone" DOUBLE PRECISION,
  "Time on Ball_Offense Zone" DOUBLE PRECISION,
  "Behind Ball_All Zones" DOUBLE PRECISION,
  "Behind Ball_Defense Zone" DOUBLE PRECISION,
  "Behind Ball_Neutral Zone" DOUBLE PRECISION,
  "Behind Ball_Offense Zone" DOUBLE PRECISION,
  "Ahead of Ball_All Zones" DOUBLE PRECISION,
  "Ahead of Ball_Defense Zone" DOUBLE PRECISION,
  "Ahead of Ball_Neutral Zone" DOUBLE PRECISION,
  "Ahead of Ball_Offense Zone" DOUBLE PRECISION,
  "Average Ball Distance_All Zones" DOUBLE PRECISION,
  "Average Ball Distance_Defense Zone" DOUBLE PRECISION,
  "Average Ball Distance_Neutral Zone" DOUBLE PRECISION,
  "Average Ball Distance_Offense Zone" DOUBLE PRECISION,
  "Distance traveled_All Zones" DOUBLE PRECISION,
  "Distance traveled_Defense Zone" DOUBLE PRECISION,
  "Distance traveled_Neutral Zone" DOUBLE PRECISION,
  "Distance traveled_Offense Zone" DOUBLE PRECISION,
  "Distance traveled on ground_All Zones" DOUBLE PRECISION,
  "Distance traveled on ground_Defense Zone" DOUBLE PRECISION,
  "Distance traveled on ground_Neutral Zone" DOUBLE PRECISION,
  "Distance traveled on ground_Offense Zone" DOUBLE PRECISION,
  "Distance traveled in the air_All Zones" DOUBLE PRECISION,
  "Distance traveled in the air_Defense Zone" DOUBLE PRECISION,
  "Distance traveled in the air_Neutral Zone" DOUBLE PRECISION,
  "Distance traveled in the air_Offense Zone" DOUBLE PRECISION,
  "Distance traveled in low air_All Zones" DOUBLE PRECISION,
  "Distance traveled in low air_Defense Zone" DOUBLE PRECISION,
  "Distance traveled in low air_Neutral Zone" DOUBLE PRECISION,
  "Distance traveled in low air_Offense Zone" DOUBLE PRECISION,
  "Distance traveled in high air_All Zones" DOUBLE PRECISION,
  "Distance traveled in high air_Defense Zone" DOUBLE PRECISION,
  "Distance traveled in high air_Neutral Zone" DOUBLE PRECISION,
  "Distance traveled in high air_Offense Zone" DOUBLE PRECISION,
  "Average Speed_All Zones" DOUBLE PRECISION,
  "Average Speed_Defense Zone" DOUBLE PRECISION,
  "Average Speed_Neutral Zone" DOUBLE PRECISION,
  "Average Speed_Offense Zone" DOUBLE PRECISION,
  "Max Speed (82.8)_All Zones" DOUBLE PRECISION,
  "Max Speed (82.8)_Defense Zone" DOUBLE PRECISION,
  "Max Speed (82.8)_Neutral Zone" DOUBLE PRECISION,
  "Max Speed (82.8)_Offense Zone" DOUBLE PRECISION,
  "SuperSonic (80+)_All Zones" DOUBLE PRECISION,
  "SuperSonic (80+)_Defense Zone" DOUBLE PRECISION,
  "SuperSonic (80+)_Neutral Zone" DOUBLE PRECISION,
  "SuperSonic (80+)_Offense Zone" DOUBLE PRECISION,
  "Boost Speed (50-79)_All Zones" DOUBLE PRECISION,
  "Boost Speed (50-79)_Defense Zone" DOUBLE PRECISION,
  "Boost Speed (50-79)_Neutral Zone" DOUBLE PRECISION,
  "Boost Speed (50-79)_Offense Zone" DOUBLE PRECISION,
  "Drive Speed (1-49)_All Zones" DOUBLE PRECISION,
  "Drive Speed (1-49)_Defense Zone" DOUBLE PRECISION,
  "Drive Speed (1-49)_Neutral Zone" DOUBLE PRECISION,
  "Drive Speed (1-49)_Offense Zone" DOUBLE PRECISION,
  "Stopped_All Zones" DOUBLE PRECISION,
  "Stopped_Defense Zone" DOUBLE PRECISION,
  "Stopped_Neutral Zone" DOUBLE PRECISION,
  "Stopped_Offense Zone" DOUBLE PRECISION,
  "On Ground_All Zones" DOUBLE PRECISION,
  "On Ground_Defense Zone" DOUBLE PRECISION,
  "On Ground_Neutral Zone" DOUBLE PRECISION,
  "On Ground_Offense Zone" DOUBLE PRECISION,
  "In Air_All Zones" DOUBLE PRECISION,
  "In Air_Defense Zone" DOUBLE PRECISION,
  "In Air_Neutral Zone" DOUBLE PRECISION,
  "In Air_Offense Zone" DOUBLE PRECISION,
  "In Low Air_All Zones" DOUBLE PRECISION,
  "In Low Air_Defense Zone" DOUBLE PRECISION,
  "In Low Air_Neutral Zone" DOUBLE PRECISION,
  "In Low Air_Offense Zone" DOUBLE PRECISION,
  "In High Air_All Zones" DOUBLE PRECISION,
  "In High Air_Defense Zone" DOUBLE PRECISION,
  "In High Air_Neutral Zone" DOUBLE PRECISION,
  "In High Air_Offense Zone" DOUBLE PRECISION,
  "Average Boost_All Zones" DOUBLE PRECISION,
  "Average Boost_Defense Zone" DOUBLE PRECISION,
  "Average Boost_Neutral Zone" DOUBLE PRECISION,
  "Average Boost_Offense Zone" DOUBLE PRECISION,
  "Empty (0)_All Zones" DOUBLE PRECISION,
  "Empty (0)_Defense Zone" DOUBLE PRECISION,
  "Empty (0)_Neutral Zone" DOUBLE PRECISION,
  "Empty (0)_Offense Zone" DOUBLE PRECISION,
  "Low (0-33)_All Zones" DOUBLE PRECISION,
  "Low (0-33)_Defense Zone" DOUBLE PRECISION,
  "Low (0-33)_Neutral Zone" DOUBLE PRECISION,
  "Low (0-33)_Offense Zone" DOUBLE PRECISION,
  "Medium (34-66)_All Zones" DOUBLE PRECISION,
  "Medium (34-66)_Defense Zone" DOUBLE PRECISION,
  "Medium (34-66)_Neutral Zone" DOUBLE PRECISION,
  "Medium (34-66)_Offense Zone" DOUBLE PRECISION,
  "High (67-100)_All Zones" DOUBLE PRECISION,
  "High (67-100)_Defense Zone" DOUBLE PRECISION,
  "High (67-100)_Neutral Zone" DOUBLE PRECISION,
  "High (67-100)_Offense Zone" DOUBLE PRECISION,
  "Full (100)_All Zones" DOUBLE PRECISION,
  "Full (100)_Defense Zone" DOUBLE PRECISION,
  "Full (100)_Neutral Zone" DOUBLE PRECISION,
  "Full (100)_Offense Zone" DOUBLE PRECISION,
  "Boost Gained_All Zones" DOUBLE PRECISION,
  "Boost Gained_Defense Zone" DOUBLE PRECISION,
  "Boost Gained_Neutral Zone" DOUBLE PRECISION,
  "Boost Gained_Offense Zone" DOUBLE PRECISION,
  "Boost Lost_All Zones" DOUBLE PRECISION,
  "Boost Lost_Defense Zone" DOUBLE PRECISION,
  "Boost Lost_Neutral Zone" DOUBLE PRECISION,
  "Boost Lost_Offense Zone" DOUBLE PRECISION,
  "Boost Lost while SuperSonic_All Zones" DOUBLE PRECISION,
  "Boost Lost while SuperSonic_Defense Zone" DOUBLE PRECISION,
  "Boost Lost while SuperSonic_Neutral Zone" DOUBLE PRECISION,
  "Boost Lost while SuperSonic_Offense Zone" DOUBLE PRECISION,
  "Boost Lost while Max Speed_All Zones" DOUBLE PRECISION,
  "Boost Lost while Max Speed_Defense Zone" DOUBLE PRECISION,
  "Boost Lost while Max Speed_Neutral Zone" DOUBLE PRECISION,
  "Boost Lost while Max Speed_Offense Zone" DOUBLE PRECISION,
  "Boost Lost on Ground_All Zones" DOUBLE PRECISION,
  "Boost Lost on Ground_Defense Zone" DOUBLE PRECISION,
  "Boost Lost on Ground_Neutral Zone" DOUBLE PRECISION,
  "Boost Lost on Ground_Offense Zone" DOUBLE PRECISION,
  "Boost Lost in Air_All Zones" DOUBLE PRECISION,
  "Boost Lost in Air_Defense Zone" DOUBLE PRECISION,
  "Boost Lost in Air_Neutral Zone" DOUBLE PRECISION,
  "Boost Lost in Air_Offense Zone" DOUBLE PRECISION,
  "Boost Lost in Low Air_All Zones" DOUBLE PRECISION,
  "Boost Lost in Low Air_Defense Zone" DOUBLE PRECISION,
  "Boost Lost in Low Air_Neutral Zone" DOUBLE PRECISION,
  "Boost Lost in Low Air_Offense Zone" DOUBLE PRECISION,
  "Boost Lost in High Air_All Zones" DOUBLE PRECISION,
  "Boost Lost in High Air_Defense Zone" DOUBLE PRECISION,
  "Boost Lost in High Air_Neutral Zone" DOUBLE PRECISION,
  "Boost Lost in High Air_Offense Zone" DOUBLE PRECISION,
  "Passes Given_All Zones" DOUBLE PRECISION,
  "Passes Given_Defense Zone" DOUBLE PRECISION,
  "Passes Given_Neutral Zone" DOUBLE PRECISION,
  "Passes Given_Offense Zone" DOUBLE PRECISION,
  "Passes Received_All Zones" DOUBLE PRECISION,
  "Passes Received_Defense Zone" DOUBLE PRECISION,
  "Passes Received_Neutral Zone" DOUBLE PRECISION,
  "Passes Received_Offense Zone" DOUBLE PRECISION,
  "50/50s_All Zones" DOUBLE PRECISION,
  "50/50s_Defense Zone" DOUBLE PRECISION,
  "50/50s_Neutral Zone" DOUBLE PRECISION,
  "50/50s_Offense Zone" DOUBLE PRECISION,
  "Possession Losses_All Zones" DOUBLE PRECISION,
  "Possession Losses_Defense Zone" DOUBLE PRECISION,
  "Possession Losses_Neutral Zone" DOUBLE PRECISION,
  "Possession Losses_Offense Zone" DOUBLE PRECISION,
  "Interceptions_All Zones" DOUBLE PRECISION,
  "Interceptions_Defense Zone" DOUBLE PRECISION,
  "Interceptions_Neutral Zone" DOUBLE PRECISION,
  "Interceptions_Offense Zone" DOUBLE PRECISION,
  "Self Touches_All Zones" DOUBLE PRECISION,
  "Self Touches_Defense Zone" DOUBLE PRECISION,
  "Self Touches_Neutral Zone" DOUBLE PRECISION,
  "Self Touches_Offense Zone" DOUBLE PRECISION,
  "Score_All Zones" DOUBLE PRECISION,
  "Score_Defense Zone" DOUBLE PRECISION,
  "Score_Neutral Zone" DOUBLE PRECISION,
  "Score_Offense Zone" DOUBLE PRECISION,
  "Goals_All Zones" DOUBLE PRECISION,
  "Goals_Defense Zone" DOUBLE PRECISION,
  "Goals_Neutral Zone" DOUBLE PRECISION,
  "Goals_Offense Zone" DOUBLE PRECISION,
  "Shots_All Zones" DOUBLE PRECISION,
  "Shots_Defense Zone" DOUBLE PRECISION,
  "Shots_Neutral Zone" DOUBLE PRECISION,
  "Shots_Offense Zone" DOUBLE PRECISION,
  "Assists_All Zones" DOUBLE PRECISION,
  "Assists_Defense Zone" DOUBLE PRECISION,
  "Assists_Neutral Zone" DOUBLE PRECISION,
  "Assists_Offense Zone" DOUBLE PRECISION,
  "Saves_All Zones" DOUBLE PRECISION,
  "Saves_Defense Zone" DOUBLE PRECISION,
  "Saves_Neutral Zone" DOUBLE PRECISION,
  "Saves_Offense Zone" DOUBLE PRECISION,
  "Kills_All Zones" DOUBLE PRECISION,
  "Kills_Defense Zone" DOUBLE PRECISION,
  "Kills_Neutral Zone" DOUBLE PRECISION,
  "Kills_Offense Zone" DOUBLE PRECISION,
  "Deaths_All Zones" DOUBLE PRECISION,
  "Deaths_Defense Zone" DOUBLE PRECISION,
  "Deaths_Neutral Zone" DOUBLE PRECISION, 
  "Deaths_Offense Zone" DOUBLE PRECISION,
  "Boost Lost When Demoed_All Zones" DOUBLE PRECISION,
  "Boost Lost When Demoed_Defense Zone" DOUBLE PRECISION,
  "Boost Lost When Demoed_Neutral Zone" DOUBLE PRECISION,
  "Boost Lost When Demoed_Offense Zone" DOUBLE PRECISION,
  "Avg Speed When Demoed_All Zones" DOUBLE PRECISION,
  "Avg Speed When Demoed_Defense Zone" DOUBLE PRECISION,
  "Avg Speed When Demoed_Neutral Zone" DOUBLE PRECISION,
  "Avg Speed When Demoed_Offense Zone" DOUBLE PRECISION,
  "Avg Speed After Killing_All Zones" DOUBLE PRECISION,
  "Avg Speed After Killing_Defense Zone" DOUBLE PRECISION,
  "Avg Speed After Killing_Neutral Zone" DOUBLE PRECISION,
  "Avg Speed After Killing_Offense Zone" DOUBLE PRECISION,
  "Avg Boost When Demoed_All Zones" DOUBLE PRECISION,
  "Avg Boost When Demoed_Defense Zone" DOUBLE PRECISION,
  "Avg Boost When Demoed_Neutral Zone" DOUBLE PRECISION,
  "Avg Boost When Demoed_Offense Zone" DOUBLE PRECISION,
  "Avg Boost When Killing_All Zones" DOUBLE PRECISION,
  "Avg Boost When Killing_Defense Zone" DOUBLE PRECISION,
  "Avg Boost When Killing_Neutral Zone" DOUBLE PRECISION,
  "Avg Boost When Killing_Offense Zone" DOUBLE PRECISION,
  "Small Pads Collected_All Zones" DOUBLE PRECISION,
  "Small Pads Collected_Defense Zone" DOUBLE PRECISION,
  "Small Pads Collected_Neutral Zone" DOUBLE PRECISION,
  "Small Pads Collected_Offense Zone" DOUBLE PRECISION,
  "Big Boosts Collected_All Zones" DOUBLE PRECISION,
  "Big Boosts Collected_Defense Zone" DOUBLE PRECISION,
  "Big Boosts Collected_Neutral Zone" DOUBLE PRECISION,
  "Big Boosts Collected_Offense Zone" DOUBLE PRECISION,
  "Overfill from Small Pads_All Zones" DOUBLE PRECISION,
  "Overfill from Small Pads_Defense Zone" DOUBLE PRECISION,
  "Overfill from Small Pads_Neutral Zone" DOUBLE PRECISION,
  "Overfill from Small Pads_Offense Zone" DOUBLE PRECISION,
  "Overfill from Big Boosts_All Zones" DOUBLE PRECISION,
  "Overfill from Big Boosts_Defense Zone" DOUBLE PRECISION,
  "Overfill from Big Boosts_Neutral Zone" DOUBLE PRECISION,
  "Overfill from Big Boosts_Offense Zone" DOUBLE PRECISION,
  "Boost Gained from Small Pads_All Zones" DOUBLE PRECISION,
  "Boost Gained from Small Pads_Defense Zone" DOUBLE PRECISION,
  "Boost Gained from Small Pads_Neutral Zone" DOUBLE PRECISION,
  "Boost Gained from Small Pads_Offense Zone" DOUBLE PRECISION,
  "Boost Gained from Big Boosts_All Zones" DOUBLE PRECISION,
  "Boost Gained from Big Boosts_Defense Zone" DOUBLE PRECISION,
  "Boost Gained from Big Boosts_Neutral Zone" DOUBLE PRECISION,
  "Boost Gained from Big Boosts_Offense Zone" DOUBLE PRECISION
);
`;

export const addIngestionColumnsSql = `
ALTER TABLE stats
  ADD COLUMN IF NOT EXISTS source_file TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS ingested_at TIMESTAMPTZ NOT NULL DEFAULT now();
`;

export const addRowHashColumnSql = `
ALTER TABLE stats
  ADD COLUMN IF NOT EXISTS row_hash TEXT NOT NULL;
`;

export const createRowHashIndexSql = `
CREATE UNIQUE INDEX IF NOT EXISTS stats_row_hash_uq ON stats(row_hash);
`;

export const createFileIngestTableSql = `
CREATE TABLE IF NOT EXISTS file_ingest (
  id BIGSERIAL PRIMARY KEY,
  file_name TEXT NOT NULL,
  file_hash TEXT NOT NULL,
  file_size BIGINT NOT NULL,
  row_count INTEGER NOT NULL,
  inserted INTEGER NOT NULL,
  skipped INTEGER NOT NULL,
  errored INTEGER NOT NULL,
  ingested_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS file_ingest_hash_uq ON file_ingest(file_hash);
`;
